algoritmo "idades"

var
   nome1, nome2 : caractere
   idade1, idade2 : inteiro
   media : real

inicio
   escreval("Dados da primeira pessoa: ")
   escreva("NOME: ")
   leia(nome1)
   escreva("IDADE: ")
   leia(idade1)
   escreval("Dados da segunda pessoa: ")
   escreva("NOME: ")
   leia(nome2)
   escreva("IDADE: ")
   leia(idade2)
   
   media <- (idade1 + idade2) / 2
   
   escreval("A idade media de ", nome1, " e ", nome2, " e de", media, " anos")
   


fimalgoritmo